### ISSUE TITLE
How could we manage the unique id ?

### ISSUE THREAD

**Issue by JrmyDev** [shannah/cn1-data-access-lib#3]
Hi Shannah, I finally resolve my problem with linked table but now, I would like to import JSON data (with importJSON method) but I have a nullpointerexception when it attempt to retrieve the id of the object : it's normal because it has done a "newObject()" and the id is null. My question, how can we manage id between the model and SQLite. I mean how it is possible to ensure the uniqueness of the id and that it is not null (both in java code and database).
Thanks in advance, and thanks for this cool library :)

**Comment by shannah** [comment]
Can you post the stack trace?  What does your DAO's getId() implementation look like?

**Comment by JrmyDev** [comment]
java.lang.NullPointerException
    at com.amplitude.tablet.dao.sqlite.BaseSQLite.getId(BaseSQLite.java:65)
    at com.amplitude.tablet.dao.sqlite.BaseSQLite.getId(BaseSQLite.java:23)
    at ca.weblite.codename1.db.Importer.importSet(Importer.java:202)
    at ca.weblite.codename1.db.Importer.importSet(Importer.java:168)
    at ca.weblite.codename1.db.Importer.importJSON(Importer.java:255)
    at ca.weblite.codename1.db.DAO.importJSON(DAO.java:896)
    at ca.weblite.codename1.db.DAO.importJSON(DAO.java:900)
    at com.amplitude.tablet.ws.SynchronisationPortType$1.actionPerformed(SynchronisationPortType.java:46)
    at com.amplitude.tablet.ws.WebServiceProxy.readResponse(WebServiceProxy.java:188)
    at com.codename1.io.ConnectionRequest.performOperation(ConnectionRequest.java:429)
    at com.codename1.io.NetworkManager$NetworkThread.run(NetworkManager.java:262)
    at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)

**Comment by JrmyDev** [comment]
Apparently, It's cause by "dao.getId(existing)" return null : it's normal because a new object is created and id is null until it's persisted. (in Importer.java)

**Comment by JrmyDev** [comment]
My getId() implementation return the id of the object : 
"public long getId(BaseObject baseObject) {
        return baseObject.getId();
    }"

**Comment by JrmyDev** [comment]
Sorry it's my fault ... I use "Long type" for my baseObject's id so I need to implement like that :
"public long getId(BaseObject baseObject){
return NumberUtil.longValue(baseObject.getId());
}
